### PR TITLE
Changes from Arthur

### PR DESCRIPTION
**Pull request by arthurpsmith**
Hi Will - this is the current state of what I have - as I think I mentioned I was mostly playing around so I'm not terribly attached to any of it. And some pieces are incomplete/not working yet.

For instance I added a search method in the controller with associated model and view pages, but I know that's not working yet!

And there's a method to list individual authors of works (who may have more associated info in the orcid profile) but no link to it from the work at the moment. And some other incompletenesses here and there.

And there's a link to enter an ORCID and see the data for that person, but of course the sample server only has 1 valid ORCID at the moment so it only works for that.

Oh, and there's absolutely no error handling (you get server errors if you put in an invalid orcid or play around with the parameters on some of the pages...)

I was mainly using it to get a feel for the data we're providing/collecting here, so it might be useful in that way for others too. Or something they could expand on.

Doing the full model a better approach might be to start with one of those xml-to-java-bean converters rather than hacking around with Spring model classes as I did here. Anyway, it works to a point...

### CODE REVIEW

**Comment by wjrsimpson** [comment]
Hi Arthur,

Many thanks for this contribution.

I've just uploaded the Java code formatting rules we've been using, into the ORCID parent repository.

https://github.com/ORCID/ORCID-Parent

There are versions for Eclipse and IntelliJ. Are you using one of those IDEs? If so, can you import the rules and apply them?

Also, are you OK with your contributions being released open source under the MIT license?

Best regards,

Will

**Comment by arthurpsmith** [comment]
We use Eclipse - and yes, consider whatever I put on github free for any 
use or license, I'd probably put a CC-0 on it if I thought about it, so 
fine to release under MIT. And I won't be offended if you don't use what 
I sent in, or there's something that needs changing.

I was going to look at hooking up to the new devsandbox server, maybe 
later this week, or are you planning on doing an update to set that up? 
I assume it's just a configuration change but I haven't looked at it yet...

```
     Arthur
```

**Comment by wjrsimpson** [comment]
Hi Arthur,

I've merged your changes into the main repository.

I reformatted all XML and JSP files to match the conventions we are now using in the main ORCID code. Apologies if this causes a difficult merge for you, but I suspect it is better to standardize and take the pain as soon as possible.
- Indenting with 4 spaces
- Max line length 170 characters

I suspect you'll need to configure your Eclipse settings for XML/HTML to get these formatting rules. I am not aware of a way of exporting/importing them so you'll have to do it manually, I think.

I have also updated the maximum line length from 120 to 170 in the Eclipse formatter in ORCID-Parent, so you may want to re-import that too.

I made some minor changes to orcid.properties to make it easier to configure for the devsandbox. The default settings should now be correct for working with the devsandbox, except that you will need your own client ID and client secret.

The search functionality in JOPMTS isn't working correctly yet. As you said above, this wasn't available in the mock, so it wasn't previously possible to investigate that. Can you take a look?

Many thanks,

Will

**Comment by arthurpsmith** [comment]
I just updated to your latest - will merge in my work on adding database 
support later (if that seems a sensible thing to do). It looks like it's 
working to connect to devsandbox, so that's great, thanks! I'll look 
into the searching - I was implementing obviously without knowing quite 
how it would work so there's probably some simple thing I missed.

```
     Arthur
```

**Comment by arthurpsmith** [comment]
There's at least one configuration piece needed to get searching to work 
- in orcid.properties the line for orcidSearchUrl should be:

orcidSearchURL=${orcidApiUrl}/search/orcid-bio

(I think).

However - when I run this I then get an OAuth2 error:

"error":"redirect_uri_mismatch","error_description":"Invalid redirect: 
http://localhost:8081/jopmts/orcid/search?text=smith does not match one 
of the registered values: [http://localhost:8081/jopmts/orcid/info]"

How do you does your OAuth2 server handle the URI matching for those 
callbacks? Do we need to set up a generic callback url on the client 
side, or can I just tell it http://localhost:8081/jopmts/\* or is there 
another preferred solution?

Mummi's rails client seems to use a generic "/auth/orcid/callback" URL - 
Mummi, was that specified by omniauth or did you have to work that out 
yourself?

Also - isn't there supposed to be a tier-1 search capability that 
doesn't require authentication? How does one get to that from a client 
(it seems to be there on the front page of devsandbox)?

```
Arthur
```

**Comment by arthurpsmith** [comment]
Hi Arthur. The callback URL in my Rails app is specific to OmniAuth: /auth/orcid/callback corresponds to "/auth/:provider/callback" where :provider is whatever OmniAuth strategy/ies you've got configured. 

The search API  is described on http://dev.orcid.org/docs/query-api, under "Searching with the Tier 1 or Tier 2 API". Try curl -H 'Accept: application/orcid+xml' 'http://devsandbox.orcid.org/search/orcid-bio?q=thorisson' .

NB you'll need to request XML  or JSON format: setting the Accept header to HTML  (or opening the search URL in a browser) will return an ugly 404 right now. I reckon it's the same bug that breaks the HTML represention for profile URL retrievals (try clicking this, for example: http://devsandbox.orcid.org/0000-0003-2012-0010)  

```
    M
```

**Comment by arthurpsmith** [comment]
Ah - I hadn't noticed that edition of the doc yet, so basically

tier 1 = http://devsandbox.orcid.org/...

tier 2 = http://api.devsandbox.orcid.org/...

for the sandbox - and presumably we'll use the same structure with the 
live version?

I'll give the tier 1 another try later in the week then. Thanks,

```
Arthur
```

**Pull request merged**
